foo: yml
bar: ${foo}
my:
  list: foo, bar
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/foo
    username: sa
    password:
    driver-class-name: org.h2.Driver